version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
